# Generated by Django 4.2 on 2025-12-18 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_student_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='branding',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='student',
            name='ecommerce',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='student',
            name='seo',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='student',
            name='website',
            field=models.BooleanField(default=False),
        ),
    ]
